### ISSUE TITLE
does this thing still work? 

### ISSUE THREAD

**Issue by k1zuto** [Wraient/stanza_cracker#1]
so I downloaded the login.py and ran it and basically nothing happened so....is it still working?

**Comment by Wraient** [comment]
are you in spectra network? 
I don't live in Stanza anymore so I can't know if it still works, but this is how it works
1. you register your Mac address on spectra network
2. you get logged out of the network automatically after some time but your Mac address is still registered, so when you login with no login id using this script, it logs you in but doesn't deduct internet balance from your account.
3. you use unlimited internet

tip : you can try using logout script to log out of the network
check if you are logged in by going to the login page and if you are redirected to the login page you can run the login script and you get unlimited internet
if you see your id, you are not logged logged out.

p.s. try going to the_base_adress/logout to make the server log you out

tell me if it still works.
goodluck.

**Comment by k1zuto** [comment]
yes I live in stanza, I have registered my mac address on the network and uhhh where's the logout script, sorry I'm a complete noob at this

**Comment by Wraient** [comment]
oh sorry, the logout script is in cracker.py
just run that script it'll ask if you want to log out, it'll try to log you out, it works half of the time, it'll work better when you are automatically logged out by the server, run cracker.py and then go to login page, if you see your new log in ID, enjoy your internet.

**Comment by k1zuto** [comment]
changed the base url and this is what I got 

you are logged out, running the script now!


finding password for 23TSFBA023


not connected, checked: 0000
not connected, checked: 0001
not connected, checked: 0002
not connected, checked: 0003
not connected, checked: 0004

**Comment by k1zuto** [comment]
changed the base url and this is what I got 

you are logged out, running the script now!


finding password for 23TSFBA023


not connected, checked: 0000
not connected, checked: 0001
not connected, checked: 0002
not connected, checked: 0003
not connected, checked: 0004

**Comment by k1zuto** [comment]
uhhhh are my comments going?

**Comment by k1zuto** [comment]
when I try to run cracker.py it just auto closes also idk what is the login page you are talking about, only time I used my username and password was for the first time to sign in to the network with random mac being off

**Comment by k1zuto** [comment]
PS C:\Users\Ali\Downloads> & C:/Users/Ali/AppData/Local/Programs/Python/Python313/python.exe c:/Users/Ali/Downloads/cracker.py
Traceback (most recent call last):
  File "c:\Users\Ali\Downloads\cracker.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
PS C:\Users\Ali\Downloads> 


this is what comes when I run cracker.py in vs code (at first I just double clicked it and a window opened and auto closed)

**Comment by Wraient** [comment]
you need to install requests
run this in vscode
```
pip install requests
```
or
```
pip3 install requests
```
and then try running again after re opening cmd

**Comment by k1zuto** [comment]
so I did that and I thought I got it all sorted but then when I double clicked the python file it started with "welcome to the cracker" and then just auto closed so I ran it in vs code and this is what I got 

PS C:\Users\Ali> & C:/Users/Ali/AppData/Local/Programs/Python/Python313/python.exe c:/Users/Ali/Downloads/Cracker/cracker.py
Welcome to the password Cracker!


Traceback (most recent call last):
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 199, in _new_conn
    sock = connection.create_connection(
        (self._dns_host, self.port),
    ...<2 lines>...
        socket_options=self.socket_options,
    )
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
    ~~~~~~~~~~~~^^^^
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen   
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 495, in _make_request
    conn.request(
    ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<6 lines>...
        enforce_content_length=enforce_content_length,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 441, in request
    self.endheaders()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 1091, in _send_output
    self.send(msg)
    ~~~~~~~~~^^^^^
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 1035, in send
    self.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 279, in connect       
    self.sock = self._new_conn()
                ~~~~~~~~~~~~~~^^
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 208, in _new_conn     
    raise ConnectTimeoutError(
    ...<2 lines>...
    ) from e
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x000002CD721FB4D0>, 'Connection to 10.201.21.1 timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen   
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\retry.py", line 519, in increment     
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.201.21.1', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002CD721FB4D0>, 'Connection to 10.201.21.1 timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Ali\Downloads\Cracker\cracker.py", line 99, in <module>
    main()
    ~~~~^^
  File "c:\Users\Ali\Downloads\Cracker\cracker.py", line 37, in main
    if logged_in():
       ~~~~~~~~~^^
  File "c:\Users\Ali\Downloads\Cracker\cracker.py", line 10, in logged_in
    status_response = requests.get(base_url, allow_redirects=False)
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 589, in request        
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Ali\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='10.201.21.1', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002CD721FB4D0>, 'Connection to 10.201.21.1 timed out. (connect timeout=None)'))
PS C:\Users\Ali>

**Comment by Wraient** [comment]
okay your base url is different, when you are prompted to login into spectra network, check the url, what they are using if it's a different ip address and login url, then you need change it in the script

**Comment by Wraient** [comment]
try running the login.py script

**Comment by k1zuto** [comment]
guhhh have to remove my device and re login ig 


also running login.py literally nothing happens

**Comment by k1zuto** [comment]
starts with this 

http://10.200.82.1/login?dst=http%3A%2F%2Fwww.msftconnecttest.com%2Fredirect


and then redirects me to this 

https://alpsmp.spectra.co/alepocp/stanza/?CM=98%3ABD%3A80%3A34%3A98%3A6A&ip=10.200.82.94&ref=
